# Generated by Django 6.0.3 on 2026-04-09 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_brand_delete_brand'),
        ('categories', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='categoryattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='categoryattribute',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['group__order', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['attribute__group__order', 'attribute__order', 'attribute__name']},
        ),
        migrations.AddField(
            model_name='attribute',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_groups', to='categories.category')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.attributegroup'),
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(fields=('group', 'slug'), name='unique_attribute_slug_per_group'),
        ),
        migrations.DeleteModel(
            name='CategoryAttribute',
        ),
        migrations.AddConstraint(
            model_name='attributegroup',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_attribute_group_slug_per_category'),
        ),
    ]
