# Generated by Django 6.0.3 on 2026-04-09 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_categoryattribute_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.attributegroup'),
            preserve_default=False,
        ),
    ]
