# Generated by Django 6.0.3 on 2026-05-08 12:09

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_attribute_group'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(default='', validators=[django.core.validators.MaxLengthValidator(3000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='usage_period',
            field=models.CharField(choices=[('few_days', 'Несколько суток'), ('less_month', 'Менее месяца'), ('more_month', 'Более месяца'), ('more_3_months', 'Более 3 месяцев'), ('more_6_months', 'Более 6 месяцев'), ('more_year', 'Более года')], default='less_month', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_review_per_user_product'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
    ]
