# Generated by Django 6.0.3 on 2026-06-17 07:21

import apps.reviews.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(3000), apps.reviews.models.validate_max_15_lines]),
        ),
        migrations.AlterField(
            model_name='reviewupdate',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000), apps.reviews.models.validate_max_10_lines]),
        ),
    ]
